
import java.awt.event.WindowEvent;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Yonde
 */
public class GUIStartingUp extends javax.swing.JFrame {

    /**
     * Creates new form GUIStartingUp
     */
    public GUIStartingUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitleOfPageLabel = new javax.swing.JLabel();
        CreateNewDatabaseButton = new javax.swing.JButton();
        LoadDatabaseFileButton = new javax.swing.JButton();
        LoadTemplateDatabaseButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Select an Option");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        TitleOfPageLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TitleOfPageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleOfPageLabel.setText("Please Select an Option:");
        TitleOfPageLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        TitleOfPageLabel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                TitleOfPageLabelAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        CreateNewDatabaseButton.setText("Create New Database");
        CreateNewDatabaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateNewDatabaseButtonActionPerformed(evt);
            }
        });

        LoadDatabaseFileButton.setText("Load Database File");
        LoadDatabaseFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadDatabaseFileButtonActionPerformed(evt);
            }
        });

        LoadTemplateDatabaseButton.setText("Load Template Database (For Debugging)");
        LoadTemplateDatabaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadTemplateDatabaseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LoadDatabaseFileButton)
                    .addComponent(CreateNewDatabaseButton)
                    .addComponent(LoadTemplateDatabaseButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(TitleOfPageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(TitleOfPageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CreateNewDatabaseButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LoadDatabaseFileButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LoadTemplateDatabaseButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TitleOfPageLabelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TitleOfPageLabelAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_TitleOfPageLabelAncestorAdded

    private void CreateNewDatabaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateNewDatabaseButtonActionPerformed
        // Creates blank Database
        Main.setBeginningSelection((byte) 0);
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_CreateNewDatabaseButtonActionPerformed

    private void LoadDatabaseFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadDatabaseFileButtonActionPerformed
        // Chooses file to load
        Main.setBeginningSelection((byte) 1);
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_LoadDatabaseFileButtonActionPerformed

    private void LoadTemplateDatabaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadTemplateDatabaseButtonActionPerformed
        // Loads template Database
        Main.setBeginningSelection((byte) 2);
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_LoadTemplateDatabaseButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIStartingUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIStartingUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIStartingUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIStartingUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIStartingUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateNewDatabaseButton;
    private javax.swing.JButton LoadDatabaseFileButton;
    private javax.swing.JButton LoadTemplateDatabaseButton;
    private javax.swing.JLabel TitleOfPageLabel;
    // End of variables declaration//GEN-END:variables
}
